name: Build and Push Multi-Service Docker Images

on:
  push:
    branches:
      - "master"
      - "dev"
  pull_request:
    branches:
      - "master"
      - "dev"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push client-react-nginx
        uses: docker/build-push-action@v5
        with:
          context: ./client-react
          file: ./Dockerfile.3
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-compose-development:client-react-nginx

      - name: Build and push client-react-vite (dev)
        uses: docker/build-push-action@v5
        with:
          context: ./client-react
          file: ./Dockerfile.2
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-compose-development:client-react-vite

      - name: Build and push api-node
        uses: docker/build-push-action@v5
        with:
          context: ./api-node
          file: ./Dockerfile.4
          target: production
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-compose-development:api-node

      - name: Build and push api-golang
        uses: docker/build-push-action@v5
        with:
          context: ./api-golang
          file: ./Dockerfile.5
          target: build-production
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/docker-compose-development:api-golang